modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0-only"
[[mods]]
modId="rubidium"
version="${version}"
displayName="Rubidium"
logoFile="icon.png"
description='''
Rubidium is a Unofficial Fork of the Sodium maked to work on FML.
'''
credits="NanoLive, Asek3"
authors="CaffeineMC"

[[mods]]
modId = "sodium"
version = "0.5.2"
displayName = "Sodium"
description = '''
Done for compatibility with Fabric's addon for Sodium
'''